services:
  mysql_db:
    image: mysql
    container_name: shared_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set root password
      MYSQL_DATABASE: appliance  # Default database to be created
    ports:
      - "3306:3306"  # Expose port 3306 for MySQL connections